# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "<YourNewStrong@Passw0rd>"
      ACCEPT_EULA: "Y"
    ports: 
      - 1433:1433 
    volumes: 
        - ./data:/var/opt/mssql/data